### ISSUE TITLE
这是为啥呀，是我写错了吗？

### ISSUE THREAD

**Issue by chengcheng0325** [easyMirais/easyMirai#14]
![{1C6414F0-75A6-46a3-9619-BE900734D746}](https://github.com/easyMirais/easyMirai/assets/163224900/97565386-becd-4da1-a5ab-167fc5f6bc2b)
![{4B97634C-56CF-4a82-A6A4-01E03BCE45CB}](https://github.com/easyMirais/easyMirai/assets/163224900/44b9230a-15ca-4adb-a6ea-730c59555196)

**Comment by ExMikuPro** [comment]
请使用pip指令升级到最新版本qwq

'''pip install easyMirai==2.33.36'''

**Comment by Bartlet** [comment]
我也遇到了同样的问题
![图片](https://github.com/user-attachments/assets/cadf5bb2-18ff-4167-8520-11e50a803608)
版本已经更新到最新
![图片](https://github.com/user-attachments/assets/defb909d-ce92-469b-a897-5807b57ae495)

**Comment by ExMikuPro** [comment]
尽快会修复🔧

**Comment by ExMikuPro** [comment]
已修复该问题请使用
`pip install easyMirai==2.34.36`
升级最新版本～
