### ISSUE TITLE
[建议] 提供静默监听功能

### ISSUE THREAD

**Issue by BiDuang** [easyMirais/easyMirai#3]
若要为贵项目构建一个持续监听消息链的函数，会不可避免地持续且大量地调用 `get.message.count` 方法。而贵项目的日志记录逻辑会使每一个被调用的方法提供日志返回，这将导致对日志生成和控制台调试造成毁灭性的影响。因此，建议阁下为方法提供静默参数，若得到静默参数要求即不再返回日志。

祝安。

**Comment by ExMikuPro** [comment]
感谢阁下提供的宝贵建议！我将在不久后更新修订版本，用以解决目前现有版本的问题，添加运行模式实现自由开关日志输出和解决大量地调用` get.message.count` ，敬请期待！

**Comment by BiDuang** [comment]
请稍候，此功能的简易实现 Pull Requests 将在晚些提交，请阁下查看。

**Comment by BiDuang** [comment]
突然发现遗漏了一个重要的事情：如果只允许`get.message.count`静默，不将每一个获取消息链的函数进行静默，对于大型群聊的日志也是惨不忍睹。
调整思路后也许可以重新引入初始化`easyMirai.Mirai`实例时提供`Debug`属性？如果不提供的话，默认将所有get类静默（可以单独为每个成员再传入参数覆盖静默属性），这样应该可以使得机器人在处理信息的时候，只会对能触发操作的消息产生反应。

***如果要修改阁下项目的话，请问是直接修改项目文件即可吗？因为我注意到PyPi包分拆的文件在项目中是合并的。***

**Comment by BiDuang** [comment]
另外，阁下不如尝试一下将过往版本的文件夹从项目中删除，这样不必每次都新建一个版本文件夹而且便于在Git视窗中对比改动。如果要观察过往版本，git提供的历史查询功能已经非常强大。现在项目由于结构较为不清晰，可能会给其他开发者造成较大困扰，可以尝试优化一下项目结构。
个人建议：
- 删除过往版本，每个版本直接在相关文件上修改，仓库只存储开发文件，不再保存冗余文件。
- 在`README.md`中提供PyPi包地址而不是将构建文件存放此处
- 如果可以，尝试为常用函数添加详细注释和参数说明

祝贵项目越做越好。

**Comment by ExMikuPro** [comment]
好的，正好趁着功能还不是很复杂时将整个项目将进行重构！（有可能时间可能很长）

**Comment by ExMikuPro** [comment]
现在我遇到了一个问题：在同一个包中如何互相调用多文件，因为在2.27.36版本中项目目录很怪异，是在想不到解决办法，望指教！感谢！

**Comment by BiDuang** [comment]
我可以先把我认为比较简洁的项目结构先推上来，你们审阅后再决定要不要采用吧

**Comment by BiDuang** [comment]
> 

你是指的由于目录层级问题导致的import混乱，还是指的文件操作？如果是前者可以尝试使用相对路径导入？

**Comment by ExMikuPro** [comment]
> > 现在我遇到了一个问题：在同一个包中如何互相调用多文件，因为在2.27.36版本中项目目录很怪异，是在想不到解决办法，望指教！感谢！
> 
> 你是指的由于目录层级问题导致的import混乱，还是指的文件操作？如果是前者可以尝试使用相对路径导入？

就是目录层级import混乱，比如在a.py中调用b.py中的类在实际编写时正常，打成whl包后就会出现一些函数无法调用的情况

**Comment by BiDuang** [comment]
很遗憾，我还没有尝试过将Python项目打包成whl文件。但是这种import的问题也遇到过，解决方法可能是将import的相对路径以程序主入口文件作为基准点进行计算。
例如一个项目文件结构如下：

**Comment by BiDuang** [comment]
很遗憾，本人由于Python大型项目开发经验尚浅，因此还没有尝试过`whl`文件的打包工作。但是对于`import`引用问题倒是有遇到过，可能的解决方案是将该文件的`import`路径改写为整个项目主入口文件作为基准的相对路径。
举个例子，某项目结构如下：

- DemoProject
  - Module
     - funcA.py
     - funcB.py
  - main.py

如果只是运行`funcA.py`，并在其中使用`funcB.py`的内容。则应使用
```python
from funcB import *
```
但如果在`main.py`调用`funcA.py`，会导致`funcA.py`在尝试访问`funcB.py`找不到文件。
需要更改为：
```python
from Module.funcA import *
```
之后，程序便只能通过`main.py`入口访问，如果尝试单独调用它，也会产生错误。

希望这个经验能帮助到你。

**Comment by ExMikuPro** [comment]
> 很遗憾，本人由于Python大型项目开发经验尚浅，因此还没有尝试过`whl`文件的打包工作。但是对于`import`引用问题倒是有遇到过，可能的解决方案是将该文件的`import`路径改写为整个项目主入口文件作为基准的相对路径。 举个例子，某项目结构如下：
> 
> * DemoProject
>   
>   * Module
>     
>     * funcA.py
>     * funcB.py
>   * main.py
> 
> 如果只是运行`funcA.py`，并在其中使用`funcB.py`的内容。则应使用
> 
> ```python
> from funcB import *
> ```
> 
> 但如果在`main.py`调用`funcA.py`，会导致`funcA.py`在尝试访问`funcB.py`找不到文件。 需要更改为：
> 
> ```python
> from Module.funcA import *
> ```
> 
> 之后，程序便只能通过`main.py`入口访问，如果尝试单独调用它，也会产生错误。
> 
> 希望这个经验能帮助到你。

好的，感谢分享经验！我会将其运用到项目中☺️！
刚才在执行重构的时候，由于很久没有编写过这个项目了，导致了有些函数自己写的完全看不懂了，由于这个原因距离重构完成会需要很长时间😢
