### ISSUE TITLE
[建议] 项目结构优化

### ISSUE THREAD

**Issue by BiDuang** [easyMirais/easyMirai#5]
另外，阁下不如尝试一下将过往版本的文件夹从项目中删除，这样不必每次都新建一个版本文件夹而且便于在Git视窗中对比改动。如果要观察过往版本，git提供的历史查询功能已经非常强大。现在项目由于结构较为不清晰，可能会给其他开发者造成较大困扰，可以尝试优化一下项目结构。
个人建议：
- 删除过往版本，每个版本直接在相关文件上修改，仓库只存储开发文件，不再保存冗余文件。
- 在`README.md`中提供PyPi包地址而不是将构建文件存放此处
- 如果可以，尝试为常用函数添加详细注释和参数说明

祝贵项目越做越好。

_Originally posted by @BiDuang in https://github.com/easyMirais/easyMirai/issues/3#issuecomment-1324431505_

**Comment by ExMikuPro** [comment]
现已优化目录结构，并开通了项目Wiki进行文档管理，相关文档正在进行编写，请阁下敬请期待！
