### ISSUE TITLE
给项目添加CI/CD功能（也许）能提高项目开发集成效率

### ISSUE THREAD

**Issue by BiDuang** [easyMirais/easyMirai#6]
如题，鄙人发现阁下项目的 `Actions` 内尚未配置工作流。而阁下项目作为一个 `pypi` 包很适合使用工作流进行多平台测试和兼容性检查，并且为其他协作者快速查看版本兼容性以及构建信息，实在是极大便利。可以尝试性探索一下？

**Comment by ExMikuPro** [comment]
感谢提出的建议 ;-) 目前制作并上传了两个 ```Actions``` 脚本，包括打包时的检查和自动上传```pypi```功能，但是目前不知道应该如何测试各个函数的可用性和文件的完整性检测，如果有更好的想法欢迎PR或者留言～(ᕑᗢᓫ∗)˒
