### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by hz3271** [easyMirais/easyMirai#7]
您简直就是我的再生父母，作为一个新人，我研究了半天[Ariadne]和别的框架，我本来需求并不算高，一个能够接入chatgpt的私人定制机器人而已，看了别的大佬的完全脑壳疼。机缘巧合看到了这个，您这个连我都能看懂，还能够作修改。非常感谢！如果您有时间的话完善文档就更好了

**Comment by ExMikuPro** [comment]
> 

非常感谢您的喜欢🥰，目前文档由我来负责编写，方便交流一下目前有哪些不足嘛😊，方便进行优化～

**Comment by hz3271** [comment]
因为我比较菜，不知道该说什么。我就说我用您的框架来做些什么吧，但愿对您有用。我有一部分代码是利用gpt帮我写的，我制作了一个带有角色设定的gptqq机器人，每天早上根据天气api提供的数据口语化发送天气预报等，实事信息等，可以根据表情信息理解并回复，将部分对话利用vits转换语音输出，在8-23随机时间根据角色设定内容自由发挥引出用户下文的话。

**Comment by HexMikuMax** [comment]
> 因为我比较菜，不知道该说什么。我就说我用您的框架来做些什么吧，但愿对您有用。我有一部分代码是利用gpt帮我写的，我制作了一个带有角色设定的gptqq机器人，每天早上根据天气api提供的数据口语化发送天气预报等，实事信息等，可以根据表情信息理解并回复，将部分对话利用vits转换语音输出，在8-23随机时间根据角色设定内容自由发挥引出用户下文的话。


好滴感谢反馈～
后续会考虑在easyMirais中添加新的开源项目，针对Win32上使用的ChatGPT便捷API接口 >w< 方便更快更方便的搭建QQGPT

也可以添加我或者ExPro的联系方式一起交流学习(*≧ω≦)

**Comment by BiDuang** [comment]
> > 因为我比较菜，不知道该说什么。我就说我用您的框架来做些什么吧，但愿对您有用。我有一部分代码是利用gpt帮我写的，我制作了一个带有角色设定的gptqq机器人，每天早上根据天气api提供的数据口语化发送天气预报等，实事信息等，可以根据表情信息理解并回复，将部分对话利用vits转换语音输出，在8-23随机时间根据角色设定内容自由发挥引出用户下文的话。
> 
> 好滴感谢反馈～ 后续会考虑在easyMirais中添加新的开源项目，针对Win32上使用的ChatGPT便捷API接口 >w< 方便更快更方便的搭建QQGPT
> 
> 也可以添加我或者ExPro的联系方式一起交流学习(*≧ω≦)

阁下可以留一个电邮便于交流。
附：阁下的个人博客网站证书已过期，还请及时更换。

**Comment by hz3271** [comment]
啊，非常抱歉。我平时工作是游戏原画师，并不会经常看github。
另外额我我没有资格和大佬们站一起。我做的最多的还是用别人的库或是别人的方法来改，
..我最近在研究别的大佬写的TTS_vits文字转语音,在尝试使用[MoeGoe-Yirimirai](https://github.com/avilliai/MoeGoe-Yirimirai)
发送qq语音消息，结合进chatgptqq机器人里。感觉也是一个未来可以更新的方向
至于您所说的交流，564243117@qq.com    。说实话，我觉得各位能回复我我就受宠若惊了，我这样的新人可能并没有多少能力来协助各位。

**Comment by BiDuang** [comment]
> 啊，非常抱歉。我平时工作是游戏原画师，并不会经常看github。 另外额我我没有资格和大佬们站一起。我做的最多的还是用别人的库或是别人的方法来改， ..我最近在研究别的大佬写的TTS_vits文字转语音,在尝试使用[MoeGoe-Yirimirai](https://github.com/avilliai/MoeGoe-Yirimirai) 发送qq语音消息，结合进chatgptqq机器人里。感觉也是一个未来可以更新的方向 至于您所说的交流，[564243117@qq.com](mailto:564243117@qq.com) 。说实话，我觉得各位能回复我我就受宠若惊了，我这样的新人可能并没有多少能力来协助各位。

不必如此客气，编程本就应该是互相学习互相进步。
