### ISSUE TITLE
关于easyMirai中requests调用的urllib3 的错误解决方案

### ISSUE THREAD

**Issue by ExMikuPro** [easyMirais/easyMirai#8]

**Comment by ExMikuPro** [comment]
<img width="1370" alt="截屏2023-05-07 13 45 13" src="https://user-images.githubusercontent.com/72144156/236660077-af2a6d4c-e36a-4b77-a50e-483ea2a5c824.png">
出现此报错解决方案：

```shell
pip install urllib3==1.26.2
```
将urllib库回退到”1.26.2“版本即可

ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168

**Comment by HexMikuMax** [comment]
不光这个，现在easyMirai.get.message.count这个函数返回的data值一直都是0 ！QAQ 该修整一下了代码了awa
