### ISSUE TITLE
关于联系方式&站点的设置&项目现存的问题

### ISSUE THREAD

**Issue by HexMikuMax** [easyMirais/easyMirai#9]
> > 因为我比较菜，不知道该说什么。我就说我用您的框架来做些什么吧，但愿对您有用。我有一部分代码是利用gpt帮我写的，我制作了一个带有角色设定的gptqq机器人，每天早上根据天气api提供的数据口语化发送天气预报等，实事信息等，可以根据表情信息理解并回复，将部分对话利用vits转换语音输出，在8-23随机时间根据角色设定内容自由发挥引出用户下文的话。
> 
> 好滴感谢反馈～ 后续会考虑在easyMirais中添加新的开源项目，针对Win32上使用的ChatGPT便捷API接口 >w< 方便更快更方便的搭建QQGPT
> 
> 也可以添加我或者ExPro的联系方式一起交流学习(*≧ω≦)

阁下可以留一个电邮便于交流。
附：阁下的个人博客网站证书已过期，还请及时更换。

_Originally posted by @BiDuang in https://github.com/easyMirais/easyMirai/issues/7#issuecomment-1537443566_

**Comment by HexMikuMax** [comment]
关于联系方式的问题：各位开发者的问题欢迎发送到` sfnco-miku@outlook.com`这个邮箱地址中～如果想要及时回复的情况下可以考虑添加ExPro的企鹅：` 3177045556 `😆

sfnco.com.cn这个站点，由于年久失修～加上现在项目在更新到2.15-M1的环境下有些问题（肯能需要重新构建request部分）暂时顾不上整理维护，在之后会考虑暂时下线🫠

上面提到，由于项目的年久失修，导致最近更新到2.15-M1版本是会出现`easyMirai.get.message.*`函数无法获取信息的问题目前正在和其他开发者寻找原因😵‍💫&重新修改👩‍💻🧑‍💻，预计几天后会上线新的版本

**Comment by hz3271** [comment]
前段时间在嫁接机器人和stablediffusion，之前有一个疑问搁置了一段时间，我想问一下现在的好友发送有发送语音的功能吗？   我在那个位置看到了一个pass  😆

**Comment by HexMikuMax** [comment]
> 前段时间在嫁接机器人和stablediffusion，之前有一个疑问搁置了一段时间，我想问一下现在的好友发送有发送语音的功能吗？ 我在那个位置看到了一个pass 😆

不是不做捏，是语音只支持群聊QAQ
![AFDC167F-04B9-4020-9698-A3894C67A8F6](https://github.com/easyMirais/easyMirai/assets/102777266/cc8588a0-b1e9-4332-8283-10f945d7b863)

**Comment by hz3271** [comment]
啊啊好的，感谢回复。:  )
